/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as WorkspacesRouteImport } from "./routes/workspaces";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as ProjectsRouteImport } from "./routes/projects";
import { Route as MeRouteImport } from "./routes/me";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProjectsProjectIdRouteImport } from "./routes/projects/$projectId";
import { Route as Errors500RouteImport } from "./routes/_errors/500";
import { Route as Errors403RouteImport } from "./routes/_errors/403";
import { Route as Errors401RouteImport } from "./routes/_errors/401";
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: "/workspaces",
  path: "/workspaces",
  getParentRoute: () => rootRouteImport,
});
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
});
const ProjectsRoute = ProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
});
const MeRoute = MeRouteImport.update({
  id: "/me",
  path: "/me",
  getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: "/$projectId",
  path: "/$projectId",
  getParentRoute: () => ProjectsRoute,
});
const Errors500Route = Errors500RouteImport.update({
  id: "/_errors/500",
  path: "/500",
  getParentRoute: () => rootRouteImport,
});
const Errors403Route = Errors403RouteImport.update({
  id: "/_errors/403",
  path: "/403",
  getParentRoute: () => rootRouteImport,
});
const Errors401Route = Errors401RouteImport.update({
  id: "/_errors/401",
  path: "/401",
  getParentRoute: () => rootRouteImport,
});
const ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
};
const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
);
const rootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SignupRoute: SignupRoute,
  WorkspacesRoute: WorkspacesRoute,
  Errors401Route: Errors401Route,
  Errors403Route: Errors403Route,
  Errors500Route: Errors500Route,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes();
